services:
  - type: web
    name: gmng
    env: python
    plan: free
    branch: main
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn.conf.py app:app
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: VIMEO_ACCESS_TOKEN
        sync: false
      - key: DEEPGRAM_API_KEY
        sync: false
      - key: FLASK_ENV
        value: production
